import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <nav className="bg-pink-800 bg-blend-saturation text-blue-400 flex justify-between">
        <Link href={'/'}> Home</Link>
        <Link href={'/chat'}>speech to text</Link>
        <Link href={'/chek'}>detect face</Link>
        <Link href={'/translat'}>translate</Link>
      </nav>
        {children}
      </body>
    </html>
  );
}
